### PR TITLE
Feature/s3 upload cache control

### PR DESCRIPTION
**Pull request by aro1976**
#50 implementation of cache control.

### CODE REVIEW

**Comment by steveataws** [comment]
Thanks for doing this.

Before I go ahead and merge, I just wanted to confirm that we're not going to cause any future problems by relying on that internal function to convert the glob pattern. I can see it being used in the current vsts-task-lib but I have no visibility into how long that might stay around.

Is there any alternate or am I worrying about nothing?

**Comment by steveataws** [comment]
@aro1976, I'd like to get this into the next release of the tools - did you see my comment about the use of the internal function, and whether there is an alternative?

**Comment by steveataws** [comment]
This is a lonely PR that I'd really like to merge, if we can come to some solution on the use of the internal function.

**Comment by steveataws** [comment]
Closing due to inactivity. We'll find an alternate approach in a future release.

**Comment by ParidaPunyasloka** [comment]
Any update on this feature coming to the vsts task? This is a much-required feature and also ability to add different headers.

**Comment by tethryus** [comment]
Hello, any update on the cache control functionality?

**Comment by hunterwerlla** [comment]
We do not have any update at this time. We are taking some time to fix up the project before looking into new feature work. Please post +1s and comments on the related issue: https://github.com/aws/aws-vsts-tools/issues/50

**Pull request closed without merging**
