### PR TITLE
ECRPullImage Task: Add output variable

### PR DESCRIPTION
**Pull request by kingwill27**
## Description

Adds an output variable to the ECRPullImage task. If an output variable name is provided, the variable will be set to the full image tag that is pulled from the repository.

This change follows the pattern in the ECRPushImage task.

## Motivation

The image name is passed as an input argument, but the pulled image is prefixed with the ECR endpoint. Outputting the image tag as pulled from ECR allows subsequent tasks to easily reference the image without reconstructing the tag from the endpoint and image name.

## Issues

See #315 

## Testing

Not tested locally.

## Checklist

-   [x] I have read the **README** document
-   [x] I have read the **CONTRIBUTING** document
-   [x] My code follows the code style of this project
-   [ ] I have added tests to cover my changes
-   [x] A short description of the change has been added to the changelog using the script `npm run newChange`

## License

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by hunterwerlla** [comment]
@kingwill27 Thanks for the contribution! Can you add a reference to the issue number in the PR description and change file? Otherwise, the code looks good

**Comment by kingwill27** [comment]
@hunterwerlla I had not yet created an issue for this feature, so I made one and referenced it

**Comment by hunterwerlla** [comment]
Thanks for your contribution! This will be part of the next release.

**Comment by kingwill27** [comment]
Thank you @hunterwerlla! Is there a schedule or estimated date for the release?

**Pull request merged**
